inherit_from:
  - .rubocop/base.yml
  - .rubocop/layout.yml
  - .rubocop/metrics.yml
  - .rubocop/performance.yml
  - .rubocop/rake.yml
  - .rubocop/rspec.yml
  - .rubocop/style.yml
  - .rubocop/yard.yml
