name: Build

on:
  pull_request:
    branches:
      - main
      - '*-alpha'
      - '*-beta'
      - '*-stable'
      - '*-dev'
  push:
    branches:
      - main
      - '*-alpha'
      - '*-beta'
      - '*-stable'
      - '*-dev'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
  coverage:
    uses: ./.github/workflows/report_coverage.yml
    secrets: inherit
  package:
    uses: ./.github/workflows/package.yml
