name: Package

on:
  workflow_call:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Branch
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Build Gem
        run: bundle exec rake build
