name: Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: publish to rubygems
        env:
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
        run: |
          mkdir -p $HOME/.gem
          mkdir -p $HOME/.local/share/gem
          touch $HOME/.gem/credentials
          touch $HOME/.local/share/gem/credentials
          chmod 0600 $HOME/.gem/credentials
          chmod 0600 $HOME/.local/share/gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.local/share/gem/credentials
          gem build *.gemspec
          gem push *.gem
      - name: publish to github package registry
        env:
          GEM_HOST_API_KEY: ${{secrets.GITHUB_TOKEN}}
          OWNER: activeinteractor
        run: |
          mkdir -p $HOME/.gem
          mkdir -p $HOME/.local/share/gem
          touch $HOME/.gem/credentials
          touch $HOME/.local/share/gem/credentials
          chmod 0600 $HOME/.gem/credentials
          chmod 0600 $HOME/.local/share/gem/credentials
          printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.local/share/gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem

