name: Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: setup credentials
        env:
          RUBYGEMS_AUTH_TOKEN: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
          GPR_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}
        run: |
          mkdir -p $HOME/.gem
          mkdir -p $HOME/.local/share/gem
          touch $HOME/.gem/credentials
          touch $HOME/.local/share/gem/credentials
          chmod 0600 $HOME/.gem/credentials
          chmod 0600 $HOME/.local/share/gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_AUTH_TOKEN}\n:github: ${GPR_AUTH_TOKEN}\n" > $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_AUTH_TOKEN}\n:github: ${GPR_AUTH_TOKEN}\n" > $HOME/.local/share/gem/credentials
      - name: publish to github package registry
        env:
          OWNER: activeinteractor
        run: |
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      - name: publish to rubygems
        run: |
          gem build *.gemspec
          gem push *.gem

