name: Report Coverage

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - name: Setup Branch
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Report Coverage
        uses: paambaati/codeclimate-action@v6.0.0
        with:
          coverageCommand: bundle exec rspec --order rand
          coverageLocations: ${{ github.workspace }}/coverage/coverage.json:simplecov
