name: Security Scan

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Setup Branch
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Generate Sarif Output
        run: bundle exec rubocop --require code_scanning --display-cop-names --format CodeScanning::SarifFormatter -o rubocop.sarif

      - name: Upload Sarif Output
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rubocop.sarif
