name: Test

on:
  workflow_call:

jobs:
  test:
    name: test - ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Branch
        uses: actions/checkout@v4

      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run Tests
        run: bundle exec rspec --format documentation --order rand
    strategy:
      matrix:
        ruby-version:
          - '3.0'
          - '3.1'
          - '3.2'
